id: A32CBED7D
title: Bodhicaryāvatāra Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.764893
  last_modified_at: 2022-03-01 04:15:05.764896
