id: A32CBED7D
title: The Prayer for the Wrathful Guru Takhyung Barwa from the Heart Essence of the
  Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.806180
  last_modified_at: 2022-03-01 04:15:05.806184
