id: A32CBED7D
title: Prayer to the Lineage of Parting from the Four Attachments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.778464
  last_modified_at: 2022-03-01 04:15:05.778467
