id: A32CBED7D
title: Prayer to the Lineage of the Bodhicaryāvatāra
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.781263
  last_modified_at: 2022-03-01 04:15:05.781266
