id: A32CBED7D
title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.784312
  last_modified_at: 2022-03-01 04:15:05.784315
