id: A32CBED7D
title: A Prayer to Kindle the Three Faiths, Addressed to the Seventeen Great Paṇḍitas
  of Glorious Nālandā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.753702
  last_modified_at: 2022-03-01 04:15:05.753705
