id: A32CBED7D
title: 'A Stream of Blessing: Verses of Supplication to the Accomplished Holders of
  Mantra who Gained Realization in this Snowy Land of Tibet'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.758346
  last_modified_at: 2022-03-01 04:15:05.758351
