id: A32CBED7D
title: 'The Seed of Faith: A Prayer to the Sublime Ones'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.807985
  last_modified_at: 2022-03-01 04:15:05.807988
