id: A32CBED7D
title: Invoking the Blessings of the Kagyü Lineage—‘Dorjechang Thungma’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.767363
  last_modified_at: 2022-03-01 04:15:05.767366
