id: A32CBED7D
title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s Teachings
  in Tibet'
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.797238
  last_modified_at: 2022-03-01 04:15:05.797241
