id: A32CBED7D
title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the Heart
  Essence of the Vast Expanse from the Great Perfection'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.761652
  last_modified_at: 2022-03-01 04:15:05.761655
