id: A32CBED7D
title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer to the
  Wisdom Ḍākinī Dechen Gyalmo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.811708
  last_modified_at: 2022-03-01 04:15:05.811710
