id: A32CBED7D
title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme VidyÄdharas
  of India'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.748901
  last_modified_at: 2022-03-01 04:15:05.748905
