id: A32CBED7D
title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret Practice
  of the Great Compassionate One, Natural Liberation of Suffering'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.787144
  last_modified_at: 2022-03-01 04:15:05.787147
