id: A32CBED7D
title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.815792
  last_modified_at: 2022-03-01 04:15:05.815795
