id: A32CBED7D
title: A Concise Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.745885
  last_modified_at: 2022-03-01 04:15:05.745893
