id: A32CBED7D
title: Supplement to the Lineage Prayer for the Lamdré Instructions Composed by Tsarchen
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.788507
  last_modified_at: 2022-03-01 04:15:05.788510
