id: A32CBED7D
title: The Lineage Prayer for the Natural Liberation of Grasping (Dzinpa Rangdrol)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.804597
  last_modified_at: 2022-03-01 04:15:05.804600
