id: A32CBED7D
title: Supplication to the Lineage of the Heart Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.792680
  last_modified_at: 2022-03-01 04:15:05.792683
