id: A32CBED7D
title: Mindrolling Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.768683
  last_modified_at: 2022-03-01 04:15:05.768686
