id: A32CBED7D
title: The Brief Ḍākinī Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:15:05.794070
  last_modified_at: 2022-03-01 04:15:05.794072
